# Generated by Django 3.1.1 on 2022-01-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='minAmount',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
