# Generated by Django 3.1.1 on 2022-02-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220214_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
