# Generated by Django 3.1.1 on 2022-02-15 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20220214_0647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='new_weight',
            new_name='net_weight',
        ),
    ]
