# Generated by Django 3.1.1 on 2022-02-15 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20220215_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bundle',
        ),
        migrations.RemoveField(
            model_name='product',
            name='on_sale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='on_sale_final_day',
        ),
        migrations.RemoveField(
            model_name='product',
            name='on_sale_init_day',
        ),
        migrations.RemoveField(
            model_name='product',
            name='point_needed',
        ),
        migrations.RemoveField(
            model_name='product',
            name='promotional',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reward',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax',
        ),
    ]
