# Generated by Django 3.1.1 on 2022-02-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20220215_1905'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='added_in',
        ),
        migrations.RemoveField(
            model_name='product',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
        migrations.RemoveField(
            model_name='product',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='modified_in',
        ),
        migrations.RemoveField(
            model_name='product',
            name='taxation',
        ),
        migrations.AlterField(
            model_name='product',
            name='gross_weight',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='net_weight',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
    ]
