# Generated by Django 3.1.1 on 2022-02-15 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20220215_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='low_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reserved_stock',
        ),
    ]
