# Generated by Django 3.1.1 on 2022-02-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20220215_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.IntegerField(default=15, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.CharField(max_length=100),
        ),
    ]
