# Generated by Django 3.1.1 on 2022-02-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20220215_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('items', models.TextField()),
                ('customer', models.CharField(default='unknown', max_length=100)),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='store.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_supplier',
            field=models.ManyToManyField(to='store.Supplier'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax',
            field=models.IntegerField(default=15),
        ),
    ]
