# Generated by Django 3.1.1 on 2022-03-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20220217_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
